.PHONY: clean All

All:
	@echo "----------Building project:[ BinarySearchTrees - Debug ]----------"
	@cd "Trees" && "$(MAKE)" -f  "BinarySearchTrees.mk"
clean:
	@echo "----------Cleaning project:[ BinarySearchTrees - Debug ]----------"
	@cd "Trees" && "$(MAKE)" -f  "BinarySearchTrees.mk" clean
