.PHONY: clean All

All:
	@echo "----------Building project:[ Graphs - Debug ]----------"
	@cd "Graphs" && "$(MAKE)" -f  "Graphs.mk"
clean:
	@echo "----------Cleaning project:[ Graphs - Debug ]----------"
	@cd "Graphs" && "$(MAKE)" -f  "Graphs.mk" clean
